---
front_image: gabicunha7/front-kento-cafe:latest
front_container_name: cafeteria-front
front_host_port: 80
front_container_port: 80


front_dockerhub_login: false
front_dockerhub_username: ""
front_dockerhub_password: ""
